// LOCKED — see PHASES/PHASE-4.md "Locked: ISO 20022 response code mapping".
// Single source of truth for the rail's response-code taxonomy. Adapters
// (pacs.002 / pacs.004 / 8583 0210), the authorization pipeline, the
// orchestrator, recovery, and reversals all reference these tables. Do not
// invent codes locally.

// Rail-internal codes — used in transactions.reason_code, response
// envelopes, audit events.
export const RAIL_CODES = Object.freeze({
  SUCCESS: 'SUCCESS',
  BENEFICIARY_ACCOUNT_NOT_FOUND: 'BENEFICIARY_ACCOUNT_NOT_FOUND',
  BENEFICIARY_ACCOUNT_CLOSED: 'BENEFICIARY_ACCOUNT_CLOSED',
  BENEFICIARY_ACCOUNT_BLOCKED: 'BENEFICIARY_ACCOUNT_BLOCKED',
  TRANSACTION_FORBIDDEN: 'TRANSACTION_FORBIDDEN',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  DUPLICATE: 'DUPLICATE',
  INVALID_END_CUSTOMER: 'INVALID_END_CUSTOMER',
  INVALID_DATE: 'INVALID_DATE',
  SETTLEMENT_FAILED: 'SETTLEMENT_FAILED',
  INVALID_FORMAT: 'INVALID_FORMAT',
  BENEFICIARY_DECEASED: 'BENEFICIARY_DECEASED',
  REGULATORY: 'REGULATORY',
  CUTOFF_TIME: 'CUTOFF_TIME',
  OPERATOR_KILL_SWITCH: 'OPERATOR_KILL_SWITCH',
  RAIL_INTERNAL_ERROR: 'RAIL_INTERNAL_ERROR',
  TIMEOUT: 'TIMEOUT',
  UNREACHABLE: 'UNREACHABLE'
});

// Rail state → ISO 20022 transaction status code (used in pacs.002 TxSts).
export const STATE_TO_ISO_STATUS = Object.freeze({
  RECEIVED: 'RCVD',
  AUTHORIZED: 'ACTC',
  ROUTED: 'ACSP',
  CREDIT_LEG_PENDING: 'ACSP',
  CONFIRMED: 'ACSC',
  PENDING_RECONCILIATION: 'PDNG',
  REJECTED: 'RJCT',
  FAILED: 'RJCT',
  REVERSED: 'ACSC'
});

// Rail reason → ISO 20022 reason code (used in pacs.002 StsRsnInf/Rsn/Cd).
export const REASON_TO_ISO_REASON = Object.freeze({
  BENEFICIARY_ACCOUNT_NOT_FOUND: 'AC01',
  BENEFICIARY_ACCOUNT_CLOSED: 'AC04',
  BENEFICIARY_ACCOUNT_BLOCKED: 'AC06',
  TRANSACTION_FORBIDDEN: 'AG01',
  INSUFFICIENT_FUNDS: 'AM04',
  DUPLICATE: 'AM05',
  INVALID_END_CUSTOMER: 'BE01',
  INVALID_DATE: 'DT01',
  SETTLEMENT_FAILED: 'ED05',
  INVALID_FORMAT: 'FF01',
  BENEFICIARY_DECEASED: 'MD07',
  REGULATORY: 'RR04',
  CUTOFF_TIME: 'TM01',
  OPERATOR_KILL_SWITCH: 'RR04',
  RAIL_INTERNAL_ERROR: 'XT99',
  TIMEOUT: 'XT99',
  UNREACHABLE: 'XT99'
});

// Result categories for routing decisions (drives recovery vs. terminal).
export const CATEGORY = Object.freeze({
  TERMINAL_FAIL: 'TERMINAL_FAIL',
  RETRYABLE_FAIL: 'RETRYABLE_FAIL',
  AMBIGUOUS: 'AMBIGUOUS',
  TERMINAL_SUCCESS: 'TERMINAL_SUCCESS'
});

export const REASON_TO_CATEGORY = Object.freeze({
  BENEFICIARY_ACCOUNT_NOT_FOUND: 'TERMINAL_FAIL',
  BENEFICIARY_ACCOUNT_CLOSED: 'TERMINAL_FAIL',
  BENEFICIARY_ACCOUNT_BLOCKED: 'TERMINAL_FAIL',
  TRANSACTION_FORBIDDEN: 'TERMINAL_FAIL',
  INSUFFICIENT_FUNDS: 'TERMINAL_FAIL',
  DUPLICATE: 'TERMINAL_FAIL',
  INVALID_END_CUSTOMER: 'TERMINAL_FAIL',
  INVALID_DATE: 'TERMINAL_FAIL',
  SETTLEMENT_FAILED: 'RETRYABLE_FAIL',
  INVALID_FORMAT: 'TERMINAL_FAIL',
  BENEFICIARY_DECEASED: 'TERMINAL_FAIL',
  REGULATORY: 'TERMINAL_FAIL',
  CUTOFF_TIME: 'TERMINAL_FAIL',
  OPERATOR_KILL_SWITCH: 'TERMINAL_FAIL',
  RAIL_INTERNAL_ERROR: 'AMBIGUOUS',
  TIMEOUT: 'AMBIGUOUS',
  UNREACHABLE: 'AMBIGUOUS'
});

export const isoStatusFor = (state) => STATE_TO_ISO_STATUS[state];
export const isoReasonFor = (railReason) => REASON_TO_ISO_REASON[railReason] || 'XT99';
export const categoryFor = (railReason) => REASON_TO_CATEGORY[railReason] || 'AMBIGUOUS';
